# -*- coding: utf-8 -*-
"""
Générateur des 150 questions proposées pour le Jeu 3 :
- 100 questions de Classe 5 (A caractère sexuel)
- 50 questions de Classe 9 (Interdits / Fantasmes)
"""

QUESTIONS_CLASSE_5 = [
    # --- Pratiques & Sensualité (25 questions) ---
    (0, "Sexualité", "Pratiques", "M", "Accorder une importance primordiale aux préliminaires lents et prolongés."),
    (0, "Sexualité", "Pratiques", "M", "Explorer les massages sensuels intégraux avec des huiles chaudes."),
    (0, "Sexualité", "Pratiques", "M", "Varier fréquemment les rythmes et intensités durant l'étreinte."),
    (0, "Sexualité", "Pratiques", "M", "Pratiquer des caresses légères et effleurements avant tout contact plus intime."),
    (0, "Sexualité", "Pratiques", "M", "Prolonger le plaisir en sachant ralentir avant l'orgasme."),
    (0, "Sexualité", "Pratiques", "M", "Préférer les baisers passionnés et profonds tout au long des rapports."),
    (0, "Sexualité", "Pratiques", "M", "Aimer explorer chaque recoin du corps de l'autre avec curiosité."),
    (0, "Sexualité", "Pratiques", "M", "Donner du plaisir oral avec passion et enthousiasme."),
    (0, "Sexualité", "Pratiques", "M", "Recevoir du plaisir oral de façon détendue et abandonnée."),
    (0, "Sexualité", "Pratiques", "M", "Apprécier la sensualité des baisers dans le cou, la nuque et les épaules."),
    (0, "Sexualité", "Pratiques", "G", "Les caresses sur les zones érogènes secondaires (mains, pieds, dos)."),
    (0, "Sexualité", "Pratiques", "M", "Prendre une douche ou un bain érotique à deux."),
    (0, "Sexualité", "Pratiques", "M", "Expérimenter différentes positions intimes pour renouveler les sensations."),
    (0, "Sexualité", "Pratiques", "M", "Aimer alterner entre douceur tendre et étreintes passionnées."),
    (0, "Sexualité", "Pratiques", "M", "Prendre le temps d'un câlin intime et complice après l'amour."),
    (0, "Sexualité", "Pratiques", "G", "L'utilisation de glaces, chaleurs ou contrastes thermiques sur la peau."),
    (0, "Sexualité", "Pratiques", "M", "Masser sensuellement le cuir chevelu et le visage pendant les préliminaires."),
    (0, "Sexualité", "Pratiques", "M", "Faire durer les étreintes intimes sans précipitation ni objectif de performance."),
    (0, "Sexualité", "Pratiques", "M", "Explorer les caresses simultanées pour une montée partagée."),
    (0, "Sexualité", "Pratiques", "G", "L'intimité peau contre peau sans vêtements pendant le sommeil."),
    (1, "Sexualité", "Pratiques", "M", "Être très attentif aux réactions et frissons de votre partenaire féminine."),
    (1, "Sexualité", "Pratiques", "M", "Savoir prendre le temps de guider délicatement votre partenaire vers l'extase."),
    (2, "Sexualité", "Pratiques", "M", "Guider votre partenaire par des gestes pour lui indiquer ce qui vous comble."),
    (2, "Sexualité", "Pratiques", "M", "Apprécier les étreintes fermes et enveloppantes de votre partenaire masculin."),
    (0, "Sexualité", "Pratiques", "M", "Exprimer physiquement son attachement amoureux à travers l'intimité corporelle."),

    # --- Désir & Séduction Intime (20 questions) ---
    (0, "Sexualité", "Désir", "M", "Prendre l'initiative de séduire son partenaire de manière impromptue."),
    (0, "Sexualité", "Désir", "M", "Créer une tension érotique tout au long de la journée par de petits signaux."),
    (0, "Sexualité", "Désir", "M", "Se laisser surprendre et désirer dans des moments inattendus du quotidien."),
    (0, "Sexualité", "Désir", "G", "Les regards intenses et complices qui en disent long sans un mot."),
    (0, "Sexualité", "Désir", "M", "Aimer être courtisé(e) et séduit(e) avec délicatesse et audace."),
    (0, "Sexualité", "Désir", "M", "Porter une attention particulière à sa lingerie ou tenue pour éveiller le désir."),
    (0, "Sexualité", "Désir", "M", "Se déshabiller mutuellement avec lenteur et théâtralité."),
    (0, "Sexualité", "Désir", "M", "Ressentir une attirance magnétique irrésistible envers son/sa partenaire."),
    (0, "Sexualité", "Désir", "G", "Le parfum corporel enivrant et naturel de la personne aimée."),
    (0, "Sexualité", "Désir", "M", "Aimer se savoir ardemment désiré(e) par l'autre."),
    (0, "Sexualité", "Désir", "M", "Initier des rapprochements tactiles audacieux en toute intimité."),
    (0, "Sexualité", "Désir", "M", "Exprimer son désir de vive voix pour décupler l'excitation de l'autre."),
    (0, "Sexualité", "Désir", "M", "Apprécier les préliminaires visuels (déshabillage, danse intime)."),
    (0, "Sexualité", "Désir", "G", "La voix rauque ou les chuchotements suggestifs au creux de l'oreille."),
    (1, "Sexualité", "Désir", "M", "Faire des compliments spontanés sur la beauté sensuelle de sa partenaire."),
    (1, "Sexualité", "Désir", "M", "Montrer clairement et avec passion son désir pour sa compagne."),
    (2, "Sexualité", "Désir", "M", "Prendre pleinement l'initiative du premier pas amoureux et sensuel."),
    (2, "Sexualité", "Désir", "M", "Se sentir belle, rayonnante et pleinement désirable dans le regard de l'autre."),
    (0, "Sexualité", "Désir", "M", "Cultiver le mystère et la séduction même après plusieurs années de couple."),
    (0, "Sexualité", "Désir", "M", "Sentir que le désir amoureux renforce l'harmonie globale du couple."),

    # --- Communication & Connexion Émotionnelle (20 questions) ---
    (0, "Sexualité", "Communication", "M", "Exprimer librement et simplement ce qui procure le plus de plaisir."),
    (0, "Sexualité", "Communication", "M", "Parler ouvertement de ses fantasmes sans crainte d'être jugé(e)."),
    (0, "Sexualité", "Communication", "M", "Demander avec tendresse à son partenaire ce qu'il/elle aimerait explorer."),
    (0, "Sexualité", "Communication", "M", "Échanger des confidences intimes sur l'oreiller après un moment d'intimité."),
    (0, "Sexualité", "Communication", "G", "Les mots doux et coquins murmurés pendant l'amour."),
    (0, "Sexualité", "Communication", "M", "Rire ensemble d'un petit imprévu sans casser la complicité érotique."),
    (0, "Sexualité", "Communication", "M", "Considérer la complicité émotionnelle comme le moteur essentiel du plaisir."),
    (0, "Sexualité", "Communication", "M", "Se sentir totalement en confiance pour lâcher prise sans aucune réserve."),
    (0, "Sexualité", "Communication", "M", "Savoir exprimer un refus avec douceur et respect mutuel sans frustration."),
    (0, "Sexualité", "Communication", "M", "S'intéresser aux lectures ou conversations sur l'épanouissement sexuel."),
    (0, "Sexualité", "Communication", "M", "Remercier son partenaire pour le plaisir partagé après l'étreinte."),
    (0, "Sexualité", "Communication", "M", "Avoir des codes ou regards secrets pour signifier son envie complice."),
    (0, "Sexualité", "Communication", "G", "La franchise totale sur ses ressentis physiques et émotionnels."),
    (0, "Sexualité", "Communication", "M", "Accueillir les désirs de l'autre avec ouverture d'esprit et curiosité bienveillante."),
    (1, "Sexualité", "Communication", "M", "Écouter attentivement les confidences intimes de votre partenaire féminine."),
    (1, "Sexualité", "Communication", "M", "Rassurer sa partenaire sur son corps et valoriser sa sensualité."),
    (2, "Sexualité", "Communication", "M", "Exprimer sans fausse pudeur ses zones de plaisir privilégiées."),
    (2, "Sexualité", "Communication", "M", "Ressentir une sécurité émotionnelle absolue pour explorer son intimité."),
    (0, "Sexualité", "Communication", "M", "Débriefer avec tendresse et humour d'une nouvelle expérience à deux."),
    (0, "Sexualité", "Communication", "M", "Construire une harmonie intime évolutive et complice au fil du temps."),

    # --- Ambiance & Érotisme des Sens (20 questions) ---
    (0, "Sexualité", "Sensualité", "G", "La lumière tamisée des bougies pour créer une atmosphère intimiste."),
    (0, "Sexualité", "Sensualité", "G", "Une musique douce ou sensuelle en arrière-plan pendant l'amour."),
    (0, "Sexualité", "Sensualité", "M", "L'obscurité totale pour décupler les sensations tactiles et auditives."),
    (0, "Sexualité", "Sensualité", "M", "Faire l'amour en plein jour pour profiter de la beauté visuelle des corps."),
    (0, "Sexualité", "Sensualité", "G", "La texture des draps de soie, de satin ou de coton frais sur la peau nue."),
    (0, "Sexualité", "Sensualité", "M", "Associer la dégustation d'un mets raffiné (fraises, chocolat) au jeu érotique."),
    (0, "Sexualité", "Sensualité", "M", "Se parfumer discrètement avant un rendez-vous amoureux intime."),
    (0, "Sexualité", "Sensualité", "M", "Partager une coupe de champagne ou un verre complice au lit."),
    (0, "Sexualité", "Sensualité", "M", "La sensualité de faire l'amour devant un feu de cheminée."),
    (0, "Sexualité", "Sensualité", "M", "Laisser planer un parfum d'ambiance envoûtant dans la chambre."),
    (0, "Sexualité", "Sensualité", "G", "Les miroirs qui reflètent les étreintes et mouvements complices."),
    (0, "Sexualité", "Sensualité", "M", "Profiter des bruits de la nature (pluie, vagues) lors d'un moment intime."),
    (0, "Sexualité", "Sensualité", "M", "Créer un véritable rituel amoureux raffiné pour une soirée privilégiée."),
    (0, "Sexualité", "Sensualité", "M", "Accorder de l'importance au confort moelleux et à l'esthétique du lit."),
    (1, "Sexualité", "Sensualité", "M", "Préparer une ambiance soignée et chaleureuse pour accueillir sa partenaire."),
    (1, "Sexualité", "Sensualité", "M", "Prendre plaisir à contempler amoureusement le corps de sa compagne."),
    (2, "Sexualité", "Sensualité", "M", "Se draper dans des étoffes douces et soyeuses qui magnifient la féminité."),
    (2, "Sexualité", "Sensualité", "M", "Être particulièrement sensible à la chaleur protectrice des bras masculins."),
    (0, "Sexualité", "Sensualité", "G", "L'ambiance feutrée d'une chambre d'hôtel lors d'une escapade à deux."),
    (0, "Sexualité", "Sensualité", "M", "S'immerger dans un univers sensoriel riche stimulant tous les sens à la fois."),

    # --- Rythme, Spontanéité & Fréquence (15 questions) ---
    (0, "Sexualité", "Rythme", "M", "Préférer les réveils câlins et l'amour spontané au saut du lit."),
    (0, "Sexualité", "Rythme", "M", "Apprécier la passion nocturne prolongée jusqu'au bout de la nuit."),
    (0, "Sexualité", "Rythme", "M", "Les câlins impromptus en milieu de journée le week-end."),
    (0, "Sexualité", "Rythme", "M", "Aimer la fougue et la rapidité d'une étreinte passionnée et imprévue."),
    (0, "Sexualité", "Rythme", "M", "Prendre plusieurs heures pour une séance intime d'exploration approfondie."),
    (0, "Sexualité", "Rythme", "G", "La régularité fréquente des moments d'intimité dans la semaine."),
    (0, "Sexualité", "Rythme", "M", "Trouver que la qualité et l'intensité priment toujours sur la fréquence."),
    (0, "Sexualité", "Rythme", "M", "Profiter des vacances pour décupler la liberté et le rythme intime."),
    (0, "Sexualité", "Rythme", "M", "Retrouver une ardeur décuplée après une brève période d'absence mutuelle."),
    (0, "Sexualité", "Rythme", "M", "Savoir adapter le tempo selon la fatigue ou la forme de son partenaire."),
    (1, "Sexualité", "Rythme", "M", "Maintenir une vigueur et une fougue spontanée dans l'intimité du couple."),
    (1, "Sexualité", "Rythme", "M", "Être toujours prêt à répondre avec passion aux avances de sa partenaire."),
    (2, "Sexualité", "Rythme", "M", "Avoir besoin d'un temps d'installation mentale pour monter en désir."),
    (2, "Sexualité", "Rythme", "M", "Apprécier les moments de tendresse prolongés sans obligation d'aboutissement."),
    (0, "Sexualité", "Rythme", "M", "Considérer la complicité intime comme un baromètre essentiel de vitalité.")
]

QUESTIONS_CLASSE_9 = [
    # --- Fantasmes & Jeux de Rôle (20 questions) ---
    (0, "Sexualité", "Fantasmes", "M", "S'adonner à des jeux de rôle où chacun endosse un personnage séduisant."),
    (0, "Sexualité", "Fantasmes", "M", "Faire semblant d'être des inconnus qui se rencontrent pour la première fois dans un bar."),
    (0, "Sexualité", "Fantasmes", "M", "Partager en détail un fantasme secret qui n'a jamais été avoué auparavant."),
    (0, "Sexualité", "Fantasmes", "G", "Les déguisements ou tenues thématiques suggérant une domination douce ou soumission."),
    (0, "Sexualité", "Fantasmes", "M", "L'idée d'un bandeau sur les yeux pour s'abandonner complètement aux caresses de l'autre."),
    (0, "Sexualité", "Fantasmes", "M", "Explorer les liens légers (rubans de soie) pour immobiliser tendrement le partenaire."),
    (0, "Sexualité", "Fantasmes", "M", "Le fantasme d'être surpris(e) ou épié(e) dans un cadre confidentiel et protégé."),
    (0, "Sexualité", "Fantasmes", "M", "Imaginer des scénarios érotiques audacieux et les mettre en scène à deux."),
    (0, "Sexualité", "Fantasmes", "G", "Les récits ou lectures érotiques partagés à deux voix sous la couette."),
    (0, "Sexualité", "Fantasmes", "M", "Aimer inverser les rôles habituels de domination et de vulnérabilité au lit."),
    (0, "Sexualité", "Fantasmes", "M", "L'idée d'un mot de passe secret pour réguler les explorations plus audacieuses."),
    (0, "Sexualité", "Fantasmes", "M", "Se faire des confidences érotiques anonymes par écrit avant de passer à l'acte."),
    (0, "Sexualité", "Fantasmes", "M", "Intégrer des petits défis coquins ou gages amoureux au quotidien."),
    (0, "Sexualité", "Fantasmes", "G", "L'utilisation de plumes, glaçons ou matières insolites pour stimuler les sens."),
    (1, "Sexualité", "Fantasmes", "M", "Apprécier qu'une partenaire prenne l'initiative d'un jeu de rôle dominant."),
    (1, "Sexualité", "Fantasmes", "M", "Exprimer ses désirs de conquête avec fougue dans un cadre complice et consenti."),
    (2, "Sexualité", "Fantasmes", "M", "Se prêter au jeu d'une séductrice impitoyable dictant ses conditions amoureuses."),
    (2, "Sexualité", "Fantasmes", "M", "Aimer être entièrement guidée et subjuguée dans un abandon total de contrôle."),
    (0, "Sexualité", "Fantasmes", "M", "Concevoir le fantasme comme un espace de liberté absolue sans culpabilité."),
    (0, "Sexualité", "Fantasmes", "M", "Réaliser un fantasme commun de longue date qui semblait inaccessible."),

    # --- Lieux Insolites & Transgression (15 questions) ---
    (0, "Sexualité", "Partenaires", "M", "L'attrait des étreintes passionnées en pleine nature (plage isolée, forêt, clairière)."),
    (0, "Sexualité", "Partenaires", "M", "Faire l'amour dans une voiture stationnée dans un lieu panoramique et discret."),
    (0, "Sexualité", "Partenaires", "M", "L'excitation d'un rapprochement furtif dans un lieu semi-public avec risque de découverte."),
    (0, "Sexualité", "Partenaires", "G", "L'intimité complice dans un ascenseur ou escalier discret entre deux étages."),
    (0, "Sexualité", "Partenaires", "M", "L'audace d'une étreinte intime sur un balcon ou une terrasse à l'abri des regards directs."),
    (0, "Sexualité", "Partenaires", "M", "Baignade nocturne nue à deux sous les étoiles suivie d'un rapprochement sur le sable."),
    (0, "Sexualité", "Partenaires", "M", "S'éclipser discrètement d'une soirée entre amis pour un moment intime volé."),
    (0, "Sexualité", "Partenaires", "M", "Explorer les pièces inhabituelles de la maison (cuisine, salon, tapis)."),
    (0, "Sexualité", "Partenaires", "G", "L'ambiance feutrée et insolite d'une cabine d'essayage à deux."),
    (0, "Sexualité", "Partenaires", "M", "L'adrénaline liée au danger léger de se faire surprendre par des proches."),
    (1, "Sexualité", "Partenaires", "M", "Proposer spontanément à sa partenaire un lieu insolite et grisant."),
    (1, "Sexualité", "Partenaires", "M", "Aimer l'excitation d'une escapade clandestine complice avec sa compagne."),
    (2, "Sexualité", "Partenaires", "M", "Accepter avec enthousiasme de suivre son partenaire dans une aventure insolite."),
    (2, "Sexualité", "Partenaires", "M", "Ressentir une liberté jubilatoire en bravant une convention formelle."),
    (0, "Sexualité", "Partenaires", "M", "Trouver que la transgression consentie renforce puissamment la flamme amoureuse."),

    # --- Limites, Curiosités & Explorations Inédites (15 questions) ---
    (0, "Sexualité", "Limites", "M", "Intégrer des accessoires intimes raffinés conçus pour le plaisir partagé."),
    (0, "Sexualité", "Limites", "M", "Discuter avec bienveillance de la notion d'exclusivité et de liberté du désir."),
    (0, "Sexualité", "Limites", "M", "Être intrigué(e) par l'exploration de pratiques sensorielles plus intenses (BDSM doux)."),
    (0, "Sexualité", "Limites", "G", "La curiosité pour les soirées libertines ou clubs privés en simple spectateur."),
    (0, "Sexualité", "Limites", "M", "L'idée de filmer ou photographier des moments intimes pour son usage privé exclusif."),
    (0, "Sexualité", "Limites", "M", "Savoir poser des limites claires et infranchissables sans blesser son partenaire."),
    (0, "Sexualité", "Limites", "M", "Se renseigner sur le tantrisme et l'élévation spirituelle par l'énergie érotique."),
    (0, "Sexualité", "Limites", "M", "L'idée d'un accord temporaire d'ouverture pour explorer une curiosité précise."),
    (0, "Sexualité", "Limites", "G", "Les conversations sans filtre sur les tabous sexuels sociétaux."),
    (0, "Sexualité", "Limites", "M", "Considérer que tout est permis entre adultes consentants si l'amour et le respect sont préservés."),
    (1, "Sexualité", "Limites", "M", "Veiller rigoureusement au consentement enthousiaste de sa compagne à chaque étape."),
    (1, "Sexualité", "Limites", "M", "Être capable de stopper immédiatement un jeu dès le moindre signe d'inconfort."),
    (2, "Sexualité", "Limites", "M", "Faire confiance à son intuition pour autoriser ou refuser une expérience inédite."),
    (2, "Sexualité", "Limites", "M", "Se sentir totalement maîtresse de ses désirs et de ses refus à chaque instant."),
    (0, "Sexualité", "Limites", "M", "Faire de l'intimité un terrain d'exploration infini où la complicité grandit sans cesse.")
]

print(f"Total Classe 5 : {len(QUESTIONS_CLASSE_5)}")
print(f"Total Classe 9 : {len(QUESTIONS_CLASSE_9)}")
print(f"Total Général : {len(QUESTIONS_CLASSE_5) + len(QUESTIONS_CLASSE_9)}")
